name = "rolldorado-bonus-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bonus.de"
HMAC_KEY = "2987758dfd279454707521305a8b8c1f56387bf9003056880aa0af7f14b3bcb5"
COOKIE_NAME = "5wj"
PLAY_PATH = "start-now"
BUTTON_ID = "p01ae92c2888e8964bd70314fb9f1bd07"
GATE_SALT = "ba61feff73982dc8"
